/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author naty9
 */
public class ViewFindWaldo extends javax.swing.JFrame {

    public static int clickCount = 0;
    /**
     * Creates new form FindWaldo
     */
    public ViewFindWaldo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCont = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/waldo.jpg"))); // NOI18N
        jLabel2.setText("jLabelWaldo");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 50, 270, 100);

        jLabelCont.setText("0");
        jPanel1.add(jLabelCont);
        jLabelCont.setBounds(680, 70, 51, 14);

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clouds.png"))); // NOI18N
        jLabelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelFondo);
        jLabelFondo.setBounds(0, 0, 390, 200);

        jButton1.setText("Agregar Imagen");
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 330, 180, 40);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);
        jButton2.setBounds(430, 450, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseClicked
        clickCount++;
        System.out.print(Integer.toString(clickCount));
        jLabelCont.setText(Integer.toString(clickCount));
        
    }//GEN-LAST:event_jLabelFondoMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        /*JPanel panelA = new JPanel();
        panelA.setBackground(Color.red);
        panelA.setMinimumSize(new java.awt.Dimension(80,100));
        panelA.setPreferredSize(new java.awt.Dimension(80,100));
        panelA.setLayout(new javax.swing.BoxLayout(panelA, javax.swing.BoxLayout.Y_AXIS));
        System.out.println("Aqui"); */
        
        System.out.println("Bye");
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFindWaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFindWaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFindWaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFindWaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFindWaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabelCont;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
