/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controller.ControllerFindWaldo.*;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author naty9
 */
public class ViewFindWaldo extends javax.swing.JFrame {

    
    public BackgroundPanel newPanel;
    /**
     * Creates new form FindWaldo
     */
    public ViewFindWaldo() {
        initComponents();
        setFondo("src\\main\\resources\\Clouds.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCont = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelWanda = new javax.swing.JLabel();
        jLabelWoof = new javax.swing.JLabel();
        jLabelOdlaw = new javax.swing.JLabel();
        jLabelBarbablanca = new javax.swing.JLabel();
        jLabelWaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabelCont.setText("0");
        jPanel1.add(jLabelCont);
        jLabelCont.setBounds(680, 70, 51, 14);

        jButton1.setText("Agregar Imagen");
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 330, 180, 40);

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(430, 450, 73, 23);

        jLabelWanda.setText("jLabel1");
        jLabelWanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelWandaMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelWanda);
        jLabelWanda.setBounds(670, 220, 34, 14);

        jLabelWoof.setText("jLabel1");
        jLabelWoof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelWoofMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelWoof);
        jLabelWoof.setBounds(250, 200, 34, 14);

        jLabelOdlaw.setText("jLabel1");
        jLabelOdlaw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOdlawMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelOdlaw);
        jLabelOdlaw.setBounds(80, 340, 34, 14);

        jLabelBarbablanca.setText("jLabel1");
        jLabelBarbablanca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBarbablancaMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelBarbablanca);
        jLabelBarbablanca.setBounds(660, 380, 34, 14);

        jLabelWaldo.setText("jLabel1");
        jLabelWaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelWaldoMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelWaldo);
        jLabelWaldo.setBounds(480, 150, 34, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelWandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWandaMouseClicked
        clickWanda++;
        System.out.println("Wenda:" + Integer.toString(clickWanda));
        checkWin();
    }//GEN-LAST:event_jLabelWandaMouseClicked

    private void jLabelBarbablancaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBarbablancaMouseClicked
        clickBarbablanca++;
        System.out.println("Barbablanca:" + Integer.toString(clickBarbablanca));
        checkWin();
    }//GEN-LAST:event_jLabelBarbablancaMouseClicked

    private void jLabelWoofMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWoofMouseClicked
        clickWoof++;
        System.out.println("Woof:" + Integer.toString(clickWoof));
        checkWin();
    }//GEN-LAST:event_jLabelWoofMouseClicked

    private void jLabelOdlawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOdlawMouseClicked
        clickOdlaw++;
        System.out.println("Odlaw:" + Integer.toString(clickOdlaw));
        checkWin();
    }//GEN-LAST:event_jLabelOdlawMouseClicked

    private void jLabelWaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWaldoMouseClicked
        clickWaldo++;
        System.out.print("Waldo: " + Integer.toString(clickWaldo));
        checkWin();
    }//GEN-LAST:event_jLabelWaldoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void newPanelMouseClicked(java.awt.event.MouseEvent evt){
        
        clickCount++;
        System.out.print("Otro: " + Integer.toString(clickCount));
        jLabelCont.setText(Integer.toString(clickCount));
        checkWin();

        
    }
    
    public void setFondo(String imagenFondo){
        
        jLabelWaldo.setText("");
        jLabelWanda.setText("");
        jLabelWoof.setText("");
        jLabelOdlaw.setText("");
        jLabelBarbablanca.setText("");
        
        newPanel = new BackgroundPanel(imagenFondo);
        
        newPanel.setLayout(null);
        newPanel.add(jLabelCont);
        newPanel.add(jButton1);
        newPanel.add(jButton2);
        newPanel.add(jLabelWaldo);
        newPanel.add(jLabelWanda);
        newPanel.add(jLabelOdlaw);
        newPanel.add(jLabelWoof);
        newPanel.add(jLabelBarbablanca);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );
        
        newPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPanelMouseClicked(evt);
            }
        });
        
        
        pack();
        
        getContentPane().remove(jPanel1); //Solo sirve la primera vez
        getContentPane().add(newPanel);
        
        
        
        validate();
    }
    
    
    public void checkWin(){
        if(clickWaldo > 0 && clickWanda > 0 && clickWoof > 0 && clickOdlaw > 0 && clickBarbablanca > 0){
            JOptionPane.showMessageDialog(this, "Felicidades ha ganado!");
            clickCount = 0;
            clickWaldo = 0;
            clickWanda = 0;
            clickWoof = 0;
            clickOdlaw = 0;
            clickBarbablanca = 0;
            jLabelCont.setText(Integer.toString(clickCount));
        } else { 
            //Perdio
            if(clickCount > 15){
                JOptionPane.showMessageDialog(this, "Lo sentimos, ha excedido los intentos posibles.");
                clickCount = 0;
                clickWaldo = 0;
                clickWanda = 0;
                clickWoof = 0;
                clickOdlaw = 0;
                clickBarbablanca = 0;
                jLabelCont.setText(Integer.toString(clickCount));
            }
        }
    }
    
    public void cambiarFondo(String pathFondo){
        newPanel.cambiarFondo(pathFondo);
        repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFindWaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFindWaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFindWaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFindWaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFindWaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabelBarbablanca;
    public javax.swing.JLabel jLabelCont;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelOdlaw;
    public javax.swing.JLabel jLabelWaldo;
    public javax.swing.JLabel jLabelWanda;
    public javax.swing.JLabel jLabelWoof;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
